language: node_js
node_js:
  - 16.14.2
script: npm run pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES
  local_dir: pages
  keep_history: true
  on:
    branch: master
    
